# config/routes.yaml

test_api:
    path: /guidelines
    controller: App\Controller\GuidelinesController::index

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
