# config/routes.yaml

test_api:
    path: /test/test
    controller: App\Controller\TestController::test

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
